version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "Microsoft.CodeAnalysis.Analyzers"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 1
    groups:
        all-dependencies:
          patterns:
            - "*"