//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contracts.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AnalyzerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnalyzerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contracts.Analyzers.AnalyzerResources", typeof(AnalyzerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified method must be private..
        /// </summary>
        internal static string MCA1001AnalyzerDescription {
            get {
                return ResourceManager.GetString("MCA1001AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be private.
        /// </summary>
        internal static string MCA1001AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MCA1001AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified method must be private.
        /// </summary>
        internal static string MCA1001AnalyzerTitle {
            get {
                return ResourceManager.GetString("MCA1001AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified method must be within a class, struct or record, and within a namespace..
        /// </summary>
        internal static string MCA1002AnalyzerDescription {
            get {
                return ResourceManager.GetString("MCA1002AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be within type.
        /// </summary>
        internal static string MCA1002AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MCA1002AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified method must be within type.
        /// </summary>
        internal static string MCA1002AnalyzerTitle {
            get {
                return ResourceManager.GetString("MCA1002AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified method is missing the &apos;verified&apos; suffix..
        /// </summary>
        internal static string MCA1003AnalyzerDescription {
            get {
                return ResourceManager.GetString("MCA1003AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is missing the &apos;{1}&apos; suffix.
        /// </summary>
        internal static string MCA1003AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MCA1003AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified method is missing verified suffix.
        /// </summary>
        internal static string MCA1003AnalyzerTitle {
            get {
                return ResourceManager.GetString("MCA1003AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute is missing argument..
        /// </summary>
        internal static string MCA1004AnalyzerDescription {
            get {
                return ResourceManager.GetString("MCA1004AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; is missing argument.
        /// </summary>
        internal static string MCA1004AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MCA1004AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute is missing argument.
        /// </summary>
        internal static string MCA1004AnalyzerTitle {
            get {
                return ResourceManager.GetString("MCA1004AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access attribute argument must be a valid modifier..
        /// </summary>
        internal static string MCA1005AnalyzerDescription {
            get {
                return ResourceManager.GetString("MCA1005AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument at position {0} in Access attribute must be a valid modifier.
        /// </summary>
        internal static string MCA1005AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MCA1005AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access attribute argument must be a valid modifier.
        /// </summary>
        internal static string MCA1005AnalyzerTitle {
            get {
                return ResourceManager.GetString("MCA1005AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequireNotNull attribute argument must be a valid parameter name..
        /// </summary>
        internal static string MCA1006AnalyzerDescription {
            get {
                return ResourceManager.GetString("MCA1006AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument at position {0} in RequireNotNull attribute must be a valid parameter name.
        /// </summary>
        internal static string MCA1006AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MCA1006AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequireNotNull attribute argument must be a valid parameter name.
        /// </summary>
        internal static string MCA1006AnalyzerTitle {
            get {
                return ResourceManager.GetString("MCA1006AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequireNotNull attribute with Alias, Type or Name can specify only one parameter name..
        /// </summary>
        internal static string MCA1007AnalyzerDescription {
            get {
                return ResourceManager.GetString("MCA1007AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument at position {0} in RequireNotNull attribute cannot be a parameter name.
        /// </summary>
        internal static string MCA1007AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MCA1007AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequireNotNull attribute has too many arguments.
        /// </summary>
        internal static string MCA1007AnalyzerTitle {
            get {
                return ResourceManager.GetString("MCA1007AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequireNotNull attribute uses invalid alias..
        /// </summary>
        internal static string MCA1008AnalyzerDescription {
            get {
                return ResourceManager.GetString("MCA1008AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias &apos;{0}&apos; in RequireNotNull attribute is invalid.
        /// </summary>
        internal static string MCA1008AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MCA1008AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequireNotNull attribute uses invalid alias.
        /// </summary>
        internal static string MCA1008AnalyzerTitle {
            get {
                return ResourceManager.GetString("MCA1008AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequireNotNull attribute uses invalid type..
        /// </summary>
        internal static string MCA1009AnalyzerDescription {
            get {
                return ResourceManager.GetString("MCA1009AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; in RequireNotNull attribute is invalid.
        /// </summary>
        internal static string MCA1009AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MCA1009AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequireNotNull attribute uses invalid type.
        /// </summary>
        internal static string MCA1009AnalyzerTitle {
            get {
                return ResourceManager.GetString("MCA1009AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequireNotNull attribute uses invalid name..
        /// </summary>
        internal static string MCA1010AnalyzerDescription {
            get {
                return ResourceManager.GetString("MCA1010AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &apos;{0}&apos; in RequireNotNull attribute is invalid.
        /// </summary>
        internal static string MCA1010AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MCA1010AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequireNotNull attribute uses invalid name.
        /// </summary>
        internal static string MCA1010AnalyzerTitle {
            get {
                return ResourceManager.GetString("MCA1010AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require attribute argument must be valid..
        /// </summary>
        internal static string MCA1011AnalyzerDescription {
            get {
                return ResourceManager.GetString("MCA1011AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument at position {0} in Require attribute must be valid.
        /// </summary>
        internal static string MCA1011AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MCA1011AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require attribute argument must be valid.
        /// </summary>
        internal static string MCA1011AnalyzerTitle {
            get {
                return ResourceManager.GetString("MCA1011AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require attribute with DebugOnly can specify only one expression..
        /// </summary>
        internal static string MCA1012AnalyzerDescription {
            get {
                return ResourceManager.GetString("MCA1012AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument at position {0} in Require attribute cannot be an expression.
        /// </summary>
        internal static string MCA1012AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MCA1012AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require attribute has too many arguments.
        /// </summary>
        internal static string MCA1012AnalyzerTitle {
            get {
                return ResourceManager.GetString("MCA1012AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure attribute argument must be valid..
        /// </summary>
        internal static string MCA1013AnalyzerDescription {
            get {
                return ResourceManager.GetString("MCA1013AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument at position {0} in Ensure attribute must be valid.
        /// </summary>
        internal static string MCA1013AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MCA1013AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure attribute argument must be valid.
        /// </summary>
        internal static string MCA1013AnalyzerTitle {
            get {
                return ResourceManager.GetString("MCA1013AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure attribute with DebugOnly can specify only one expression..
        /// </summary>
        internal static string MCA1014AnalyzerDescription {
            get {
                return ResourceManager.GetString("MCA1014AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument at position {0} in Ensure attribute cannot be an expression.
        /// </summary>
        internal static string MCA1014AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MCA1014AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure attribute has too many arguments.
        /// </summary>
        internal static string MCA1014AnalyzerTitle {
            get {
                return ResourceManager.GetString("MCA1014AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be initialized with a call to the specified method..
        /// </summary>
        internal static string MCA2001AnalyzerDescription {
            get {
                return ResourceManager.GetString("MCA2001AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be initialized with a call to the &apos;{0}&apos; method.
        /// </summary>
        internal static string MCA2001AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MCA2001AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be initialized.
        /// </summary>
        internal static string MCA2001AnalyzerTitle {
            get {
                return ResourceManager.GetString("MCA2001AnalyzerTitle", resourceCulture);
            }
        }
    }
}
